### ISSUE TITLE
Issue running parametric umap on large data - proto limit

### ISSUE THREAD

**Issue by himaniyadav** [lmcinnes/umap#608]
I'm trying to run a basic parametric UMAP embedding on my dataset. Each image is (193, 229, 193) so flattened out is 8,530,021 dimensions. 

This is the error when trying to run `embedding = embedder.fit_transform(train_images)`.
```
raise ValueError(

    ValueError: Tried to convert 'params' to a tensor and failed. Error: Cannot create a tensor proto whose content is larger than 2GB.
```

It seems like this is just a limitation of tensorflow so I am not sure what can be done about this on your end. But I was wondering if anyone has faced something similar with large datasets and if there was a workaround for this issue?

**Comment by timsainb** [comment]
Have you tried decreasing batch_size?

**Comment by himaniyadav** [comment]
Yes, had batch_size set to the default/None before but even at 1 it's the same error message.

**Comment by timsainb** [comment]
It looks like the issue here is the tensorflow dataset / iterator being created from a numpy array, which has an upper limit of 2GB. We could try a different iterator, which would move the upper limit to the amount of data that fits in RAM. 
[1] https://stackoverflow.com/a/53382823/200663
[2] https://stackoverflow.com/a/55126482/200663

**Comment by timsainb** [comment]
This should be fixed in the PR above @himaniyadav. I added a py_function into the iterator when the dataset passed into parametric_umap is bigger than 2GB. Let me know if that works for you.

**Comment by himaniyadav** [comment]
It's still not working for me (same error message) - but I can't tell if that's because it's for some reason not recognizing the more recent PR from github. I did run `pip install git+git://github.com/lmcinnes/umap@master`

**Comment by timsainb** [comment]
I think you're right, you're probably still loading the older version.

**Comment by himaniyadav** [comment]
Okay yep, can confirm that it's fixed and I'm no longer getting that error. The process is still killed partway into the first epoch because it's taking up too much memory for my system, but that's a me problem :)

**Comment by timsainb** [comment]
It's likely still possible to optimize the code to make sure the array never gets copied. When I tried running on a very large N dataset, my memory error occurred during the graph computation step though.
